const API_URL = window.IDEABID_API_URL || localStorage.getItem('ideabid-api-url') || 'https://ideabid-1yx3.onrender.com';
const categories = ['All ideas', 'Climate', 'AI & data', 'Health', 'Future of work', 'Consumer', 'Education'];
let ideas = [];
let activeCategory='All ideas'; let search=''; let selectedIdea=null; let currentPage=1; let hasNextPage=false; let ideaSort='top';
let authMode = 'login';
const savedTheme=localStorage.getItem('ideabid-theme');
const theme=savedTheme||(window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');
document.documentElement.dataset.theme=theme;
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const getAccessToken=()=>localStorage.getItem('ideabid-access-token');
const authHeaders=()=>{const token=getAccessToken();return token?{Authorization:`Bearer ${token}`}:{}};
function renderAuthState(){const user=JSON.parse(localStorage.getItem('ideabid-user')||'null');document.querySelectorAll('.auth-trigger').forEach(button=>button.classList.toggle('hidden',Boolean(user)));const account=document.querySelector('#accountState');if(account){account.classList.toggle('hidden',!user);account.querySelector('.account-name').textContent=user?.username||user?.name||'';}}
function logout(){localStorage.removeItem('ideabid-access-token');localStorage.removeItem('ideabid-refresh-token');localStorage.removeItem('ideabid-user');renderAuthState();showToast('You have been signed out.');}
function updateThemeToggle(){const dark=document.documentElement.dataset.theme==='dark';const button=document.querySelector('#themeToggle');button.textContent=dark?'☀':'☾';button.setAttribute('aria-label',dark?'Switch to light theme':'Switch to dark theme');button.title=dark?'Switch to light theme':'Switch to dark theme';document.querySelector('meta[name="theme-color"]').content=dark?'#10151d':'#f5f2eb';}
function renderFilters(){document.querySelector('#categoryFilters').innerHTML=categories.map(c=>`<button class="filter-pill ${c===activeCategory?'active':''}" data-category="${c}">${c}</button>`).join('');document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{activeCategory=b.dataset.category;currentPage=1;renderFilters();loadIdeas()}));}
function formatCreatedAt(value){const days=Math.round((new Date(value)-Date.now())/86400000);return new Intl.RelativeTimeFormat('en',{numeric:'auto'}).format(days,'day');}
function renderIdeas(){const view=ideas.filter(i=>`${i.title} ${i.description} ${i.maker}`.toLowerCase().includes(search.toLowerCase()));document.querySelector('#ideaList').innerHTML=view.length?view.map((i,index)=>`<article class="idea-card"><div class="idea-rank">${String((currentPage-1)*10+index+1).padStart(2,'0')}</div><div class="idea-content"><div class="idea-top"><span class="category-pill ${i.category==='Climate'?'yellow':i.category==='Health'?'coral':'blue'}">${escapeHtml(i.category).toUpperCase()}</span>${i.mvp?'<span class="has-mvp">MVP ready</span>':''}${i.status!=='PUBLISHED'?`<span class="has-mvp">${escapeHtml(i.status.replace('_',' '))}</span>`:''}</div><h3 class="idea-title">${escapeHtml(i.title)}</h3><p class="idea-description">${escapeHtml(i.description)}</p><div class="idea-meta"><span class="maker-avatar ${i.color}">${i.initial}</span> ${escapeHtml(i.maker)} <span>•</span> ${formatCreatedAt(i.createdAt)}</div></div><div class="idea-side"><button class="vote-button" data-vote="${i.id}">▲ <span>${i.votes.toLocaleString()}</span></button><div class="bid-amount">${money(i.bid)}<small>highest bid</small></div>${i.status==='PUBLISHED'?`<button class="bid-button" data-bid="${i.id}">Place a bid ↗</button>`:''}</div></article>`).join(''):'<div class="empty-state">No ideas found. Try another category or search.</div>';document.querySelectorAll('[data-vote]').forEach(b=>b.addEventListener('click',()=>vote(b.dataset.vote)));document.querySelectorAll('[data-bid]').forEach(b=>b.addEventListener('click',()=>openIdeaModal(b.dataset.bid)));renderPagination();}
function renderMovers(){document.querySelector('#movers').innerHTML=ideas.slice().sort((a,b)=>b.bid-a.bid).slice(0,3).map(i=>`<div class="mover-row"><span class="mover-symbol">${i.initial}</span><div><b>${escapeHtml(i.title.split('—')[0].trim())}</b><small>▲ ${i.votes.toLocaleString()}</small></div><strong>${i.trend}</strong></div>`).join('');}
async function vote(id){const token=getAccessToken();if(!token){openAuthModal('login');showToast('Sign in to upvote an idea.');return}try{const response=await fetch(`${API_URL}/v1/ideas/${id}/upvote`,{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()}});if(response.status===401){logout();openAuthModal('login');throw new Error('Your session expired. Please sign in again.')}if(!response.ok)throw new Error();await loadIdeas();showToast('Upvoted — great ideas grow with conviction.')}catch(error){showToast(error.message||'Unable to upvote this idea.')}}
function openIdeaModal(id){if(!getAccessToken()){openAuthModal('login');showToast('Sign in before sharing an idea or creating checkout.');return}selectedIdea=id||null;document.querySelector('#ideaForm').reset();document.querySelector('#openingBid').value=id?String((ideas.find(i=>i.id===id)?.bid||0)+1):'1';document.querySelector('#ideaModal').showModal();}
function showToast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3600)}
async function submitIdea(event){event.preventDefault();const token=getAccessToken();if(!token){closeDialog(document.querySelector('#ideaModal'));openAuthModal('login');showToast('Sign in before sharing an idea or creating checkout.');return}const data=Object.fromEntries(new FormData(event.currentTarget));const amount=Number(data.bid);if(!Number.isFinite(amount)||amount<1){showToast('Your opening bid must be at least $1.');return}if(!API_URL){showToast('The API is not configured. Set the IdeaBid API URL first.');return}const button=event.currentTarget.querySelector('[type=submit]');button.disabled=true;button.textContent='Creating secure checkout…';try{const r=await fetch(`${API_URL}/v1/payments/idea-checkout`,{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify({...data,bid:amount,ideaId:selectedIdea})});const result=await r.json();if(r.status===401){logout();throw new Error('Your session expired. Please sign in again.')}if(!r.ok)throw new Error(Array.isArray(result.message)?result.message.join(', '):(result.message||'Checkout could not be created.'));if(result.checkoutUrl)window.location.assign(result.checkoutUrl);else throw new Error('Dodo did not return a checkout URL.')}catch(error){showToast(error.message||'Unable to start checkout. Please try again.')}finally{button.disabled=false;button.innerHTML='Continue to secure checkout <span>↗</span>'}}
function renderPagination(){document.querySelector('#pageStatus').textContent=`Page ${currentPage}`;document.querySelector('#previousPage').disabled=currentPage===1;document.querySelector('#nextPage').disabled=!hasNextPage;}
async function loadIdeas(){if(!API_URL){ideas=[];renderIdeas();renderMovers();return}const params=new URLSearchParams({page:String(currentPage),pageSize:'10',sort:ideaSort});if(activeCategory!=='All ideas')params.set('category',activeCategory);try{const response=await fetch(`${API_URL}/v1/ideas?${params}`);if(!response.ok)throw new Error();const result=await response.json();const mapIdea=idea=>({id:idea.id,title:idea.title,category:idea.category,description:idea.description,maker:idea.author?.name||idea.author?.username||'Anonymous',initial:(idea.author?.name||idea.author?.username||'A').charAt(0).toUpperCase(),createdAt:idea.createdAt,bid:Math.round(idea.currentBidCents/100),votes:idea._count?.upvotes||idea.upvoteCount||0,mvp:Boolean(idea.mvpDetails),status:idea.status,color:'green',trend:''});ideas=result.data.map(mapIdea);const token=getAccessToken();if(token){const mine=await fetch(`${API_URL}/v1/ideas/mine`,{headers:authHeaders()});if(mine.ok){const own=(await mine.json()).filter(idea=>idea.status!=='PUBLISHED').map(mapIdea);ideas=[...own,...ideas];}}hasNextPage=result.pagination.hasNextPage;renderIdeas();renderMovers()}catch{showToast('Unable to load ideas from the API.')}}
function setAuthMode(mode){authMode=mode;const isSignup=mode==='signup';const authTitle=document.querySelector('#authTitle');const authKicker=document.querySelector('#authKicker');const authSwitchText=document.querySelector('#authSwitchText');const authSubmit=document.querySelector('#authSubmit');const authNameWrap=document.querySelector('#authNameWrap');const switchButton=document.querySelector('.auth-switch-button');if(authNameWrap){authNameWrap.classList.toggle('hidden',!isSignup);const nameInput=authNameWrap.querySelector('input');if(nameInput){nameInput.required=isSignup;}}if(authTitle) authTitle.textContent=isSignup?'Create your account':'Log in to IdeaBid';if(authKicker) authKicker.textContent=isSignup?'JOIN IDEA BID':'WELCOME BACK';if(authSubmit) authSubmit.textContent=isSignup?'Create account':'Log in';if(authSwitchText) authSwitchText.textContent=isSignup?'Already have an account?':'Need an account?';if(switchButton){switchButton.textContent=isSignup?'Log in':'Create one';switchButton.dataset.mode=isSignup?'login':'signup';}}
function closeDialog(dialog){if(!dialog) return; if(typeof dialog.close==='function' && dialog.hasAttribute('open')){dialog.close(); return;} dialog.removeAttribute('open');}
function openAuthModal(mode='login'){const modal=document.querySelector('#authModal');const form=document.querySelector('#authForm');if(!modal||!form) return; setAuthMode(mode); form.reset(); if(typeof modal.showModal==='function'){modal.showModal();} else { modal.setAttribute('open','open'); } }
async function submitAuth(event){event.preventDefault();const form=event.currentTarget;const formData=Object.fromEntries(new FormData(form));const endpoint=authMode==='signup'?'/v1/auth/signup':'/v1/auth/signin';const payload=authMode==='signup'?{email:formData.email,name:formData.name,password:formData.password,username:(String(formData.email).split('@')[0]||'user').replace(/[^a-z0-9_]/gi,'').toLowerCase() + '_' + Math.random().toString(36).slice(2,7)}:{email:formData.email,password:formData.password};const button=form.querySelector('#authSubmit');button.disabled=true;button.textContent=authMode==='signup'?'Creating account…':'Signing in…';try{const response=await fetch(`${API_URL}${endpoint}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(Array.isArray(result.message)?result.message.join(', '):(result.message||'Authentication failed.'));if(!result.accessToken||!result.refreshToken||!result.user)throw new Error('Authentication response is incomplete.');localStorage.setItem('ideabid-access-token',result.accessToken);localStorage.setItem('ideabid-refresh-token',result.refreshToken);localStorage.setItem('ideabid-user',JSON.stringify(result.user));renderAuthState();closeDialog(document.querySelector('#authModal'));showToast(authMode==='signup'?'Account created successfully.':'Signed in successfully.');setAuthMode('login');}catch(error){showToast(error.message||'Unable to authenticate.');}finally{button.disabled=false;button.textContent=authMode==='signup'?'Create account':'Log in';}}

document.querySelector('#themeToggle').addEventListener('click',()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';localStorage.setItem('ideabid-theme',document.documentElement.dataset.theme);updateThemeToggle()});document.querySelectorAll('.auth-trigger').forEach(b=>b.addEventListener('click',()=>openAuthModal(b.dataset.mode||'login')));document.querySelectorAll('.auth-switch-button').forEach(b=>b.addEventListener('click',()=>openAuthModal(b.dataset.mode||'login')));document.querySelectorAll('.create-trigger').forEach(b=>b.addEventListener('click',()=>openIdeaModal()));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>{const dialog=b.closest('dialog'); if(dialog){closeDialog(dialog);} }));document.querySelector('#logoutButton')?.addEventListener('click',logout);document.querySelector('#ideaForm').addEventListener('submit',submitIdea);document.querySelector('#authForm').addEventListener('submit',submitAuth);document.querySelector('#searchInput').addEventListener('input',e=>{search=e.target.value;renderIdeas()});document.querySelector('#ideaSort').addEventListener('change',e=>{ideaSort=e.target.value;currentPage=1;loadIdeas()});document.querySelector('#filterButton').addEventListener('click',()=>document.querySelector('#categoryFilters').scrollIntoView({behavior:'smooth',block:'center'}));document.querySelector('#previousPage').addEventListener('click',()=>{if(currentPage>1){currentPage--;loadIdeas()}});document.querySelector('#nextPage').addEventListener('click',()=>{if(hasNextPage){currentPage++;loadIdeas()}});updateThemeToggle();setAuthMode('login');renderAuthState();renderFilters();loadIdeas();
